apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s9s4oxjpl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:6c9d7ddacd5f393e9217a2701560d7119863ede5@sha256:409de03f10b02bc4d0129118ac376dbb49c413bed5d25d78085dfb56cd31717a
          name: container-image
